import type { KnowledgeEntry } from "@/types/knowledgeEntry";

export const mtgKnowledgeBase: KnowledgeEntry[] = [
  {
    canonical: "Magic",
    aliases: ["magic", "mtg", "magic the gathering"],
    category: "game",
  },
  {
    canonical: "Near Mint",
    aliases: ["nm", "near mint", "mint"],
    category: "condition",
  },
  {
    canonical: "Lightly Played",
    aliases: ["lp", "light play", "lightly played", "sp", "slight play"],
    category: "condition",
  },
  {
    canonical: "Moderately Played",
    aliases: ["mp", "moderately played", "played"],
    category: "condition",
  },
  {
    canonical: "Heavily Played",
    aliases: ["hp", "heavily played"],
    category: "condition",
  },
  {
    canonical: "Damaged",
    aliases: ["dmg", "damaged", "poor"],
    category: "condition",
  },
  {
    canonical: "Excellent",
    aliases: ["excellent", "good", "fair"],
    category: "condition",
  },
  {
    canonical: "English",
    aliases: ["en", "eng", "english"],
    category: "language",
  },
  {
    canonical: "Japanese",
    aliases: ["jp", "jpn", "japanese"],
    category: "language",
  },
  {
    canonical: "Portuguese",
    aliases: ["pt", "por", "portuguese"],
    category: "language",
  },
  {
    canonical: "Spanish",
    aliases: ["es", "spa", "spanish"],
    category: "language",
  },
  {
    canonical: "French",
    aliases: ["fr", "fre", "french"],
    category: "language",
  },
  {
    canonical: "German",
    aliases: ["de", "ger", "german"],
    category: "language",
  },
  {
    canonical: "Italian",
    aliases: ["it", "ita", "italian"],
    category: "language",
  },
  {
    canonical: "Russian",
    aliases: ["ru", "rus", "russian"],
    category: "language",
  },
  {
    canonical: "Korean",
    aliases: ["kr", "kor", "korean"],
    category: "language",
  },
  {
    canonical: "Simplified Chinese",
    aliases: ["zhs", "simplified chinese"],
    category: "language",
  },
  {
    canonical: "Traditional Chinese",
    aliases: ["zht", "traditional chinese"],
    category: "language",
  },
  {
    canonical: "Foil",
    aliases: ["foil", "foiled"],
    category: "finish",
  },
  {
    canonical: "Nonfoil",
    aliases: ["nonfoil", "non foil", "non-foil", "nf", "regular"],
    category: "finish",
  },
  {
    canonical: "Etched",
    aliases: ["etched", "foil etched"],
    category: "finish",
  },
  {
    canonical: "Galaxy",
    aliases: ["galaxy"],
    category: "finish",
  },
  {
    canonical: "Halo",
    aliases: ["halo"],
    category: "finish",
  },
  {
    canonical: "Surge",
    aliases: ["surge", "surge foil"],
    category: "finish",
  },
  {
    canonical: "Rainbow",
    aliases: ["rainbow"],
    category: "finish",
  },
  {
    canonical: "Confetti",
    aliases: ["confetti"],
    category: "finish",
  },
  {
    canonical: "Glossy",
    aliases: ["glossy"],
    category: "finish",
  },
  {
    canonical: "Matte",
    aliases: ["matte"],
    category: "finish",
  },
  {
    canonical: "Retro",
    aliases: ["retro", "old border", "classic"],
    category: "frame",
  },
  {
    canonical: "Future",
    aliases: ["future", "future shifted"],
    category: "frame",
  },
  {
    canonical: "Borderless",
    aliases: ["borderless", "extended"],
    category: "frame",
  },
  {
    canonical: "Showcase",
    aliases: ["showcase"],
    category: "frame",
  },
  {
    canonical: "Textless",
    aliases: ["textless", "text less", "no text"],
    category: "treatment",
  },
  {
    canonical: "Anime",
    aliases: ["anime"],
    category: "treatment",
  },
  {
    canonical: "Manga",
    aliases: ["manga"],
    category: "treatment",
  },
  {
    canonical: "Full Art",
    aliases: ["full art", "extended art"],
    category: "treatment",
  },
  {
    canonical: "Serialized",
    aliases: ["serialized", "serial"],
    category: "treatment",
  },
  {
    canonical: "Invocation",
    aliases: ["invocation", "invocations"],
    category: "treatment",
  },
  {
    canonical: "Raised Foil",
    aliases: ["raised foil", "double rainbow", "neon", "oil slick"],
    category: "treatment",
  },
  {
    canonical: "Masterpiece",
    aliases: ["masterpiece", "expedition", "invention"],
    category: "treatment",
  },
  {
    canonical: "Special Guests",
    aliases: ["special guest", "special guests", "spg", "guest"],
    category: "product",
  },
  {
    canonical: "Mystical Archive",
    aliases: ["mystical archive"],
    category: "product",
  },
  {
    canonical: "Retro Artifacts",
    aliases: ["retro artifacts"],
    category: "product",
  },
  {
    canonical: "The List",
    aliases: ["the list", "list"],
    category: "product",
  },
  {
    canonical: "Booster Fun",
    aliases: ["booster fun", "fracture", "fractured"],
    category: "treatment",
  },
  {
    canonical: "Judge Promo",
    aliases: ["judge", "judge promo"],
    category: "promo",
  },
  {
    canonical: "Store Championship",
    aliases: ["store championship", "championship"],
    category: "promo",
  },
  {
    canonical: "Regional Championship",
    aliases: ["regional championship", "rcq", "pro tour", "grand prix", "gp"],
    category: "promo",
  },
  {
    canonical: "MagicFest",
    aliases: ["magicfest", "festival", "convention"],
    category: "promo",
  },
  {
    canonical: "Secret Lair",
    aliases: ["secret lair", "sld"],
    category: "promo",
  },
  {
    canonical: "Buy-a-Box",
    aliases: ["buy a box", "buy-a-box", "bab"],
    category: "promo",
  },
  {
    canonical: "Prerelease",
    aliases: ["prerelease", "promo pack", "media promo", "welcome deck"],
    category: "promo",
  },
  {
    canonical: "Launch Party",
    aliases: ["launch party", "open house", "arena promo"],
    category: "promo",
  },
  {
    canonical: "30th Anniversary",
    aliases: ["30th", "30a", "30th anniversary"],
    category: "promo",
  },
  {
    canonical: "Tarkir",
    aliases: ["tarkir", "tarkir block"],
    category: "set",
  },
  {
    canonical: "Khans of Tarkir",
    aliases: ["khans of tarkir", "khans", "ktk"],
    category: "set",
  },
  {
    canonical: "Dragons of Tarkir",
    aliases: ["dragons of tarkir", "dtk"],
    category: "set",
  },
  {
    canonical: "Fate Reforged",
    aliases: ["fate reforged", "frf"],
    category: "set",
  },
  {
    canonical: "Limited Edition Alpha",
    aliases: ["alpha", "lea"],
    category: "set",
  },
  {
    canonical: "Limited Edition Beta",
    aliases: ["beta", "leb"],
    category: "set",
  },
  {
    canonical: "Unlimited Edition",
    aliases: ["unlimited", "2ed"],
    category: "set",
  },
  {
    canonical: "Eternal Masters",
    aliases: ["ema", "eternal masters"],
    category: "set",
  },
  {
    canonical: "Modern Horizons 2",
    aliases: ["modern horizons 2"],
    category: "set",
  },
  {
    canonical: "Commander",
    aliases: ["commander", "edh"],
    category: "set",
  },
  {
    canonical: "Jumpstart",
    aliases: ["jumpstart"],
    category: "set",
  },
  {
    canonical: "Masters",
    aliases: ["masters", "modern masters"],
    category: "set",
  },
  {
    canonical: "Universes Beyond",
    aliases: ["universes beyond", "ub"],
    category: "set",
  },
  {
    canonical: "Common",
    aliases: ["common", "c"],
    category: "rarity",
  },
  {
    canonical: "Uncommon",
    aliases: ["uncommon", "u"],
    category: "rarity",
  },
  {
    canonical: "Rare",
    aliases: ["rare", "r"],
    category: "rarity",
  },
  {
    canonical: "Mythic Rare",
    aliases: ["mythic", "mythic rare", "m"],
    category: "rarity",
  },
  {
    canonical: "Special",
    aliases: ["special", "bonus"],
    category: "rarity",
  },
  {
    canonical: "PSA 10",
    aliases: ["psa10", "psa 10", "gem mint"],
    category: "grading",
  },
];

const setCodes = [
  "lea",
  "leb",
  "2ed",
  "arn",
  "atq",
  "leg",
  "drk",
  "ice",
  "mir",
  "tmp",
  "usg",
  "inv",
  "ody",
  "ons",
  "mrd",
  "chk",
  "rav",
  "tsp",
  "lrw",
  "ala",
  "zen",
  "isd",
  "rtr",
  "ths",
  "ktk",
  "bfz",
  "soi",
  "akh",
  "xln",
  "dom",
  "grn",
  "war",
  "eld",
  "iko",
  "znr",
  "khm",
  "stx",
  "afr",
  "mid",
  "vow",
  "neo",
  "snc",
  "dmu",
  "bro",
  "one",
  "mom",
  "woe",
  "lci",
  "mkm",
  "otj",
  "ltr",
  "mh1",
  "mh2",
  "mh3",
].map<KnowledgeEntry>((code) => ({
  canonical: code.toUpperCase(),
  aliases: [code],
  category: "setCode",
}));

export const mtgKnowledge = [...mtgKnowledgeBase, ...setCodes];
