import type { IndicatorMetadata } from "@/lib/intelligence/framework/IndicatorMetadata";

export const indicatorRegistry: IndicatorMetadata[] = [
  {
    id: "investment-potential",
    name: "Investment Potential",
    signalName: "InvestmentPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Scryfall Market Provider"],
    futureDependencies: ["Historical Intelligence", "Regional Intelligence"],
    explanation: "Measures long-term asset potential from current card, printing, and market context.",
  },
  {
    id: "collector-appeal",
    name: "Collector Appeal",
    signalName: "CollectorAppeal",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall"],
    futureDependencies: ["PSA", "CGC", "BGS"],
    explanation: "Measures collector desirability from printing prestige, treatment, product family, and finish.",
  },
  {
    id: "liquidity",
    name: "Liquidity",
    signalName: "Liquidity",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket", "LigaMagic"],
    explanation: "Measures how easily the asset can be resold once live marketplace depth exists.",
  },
  {
    id: "reprint-risk",
    name: "Reprint Risk",
    signalName: "ReprintRisk",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall"],
    futureDependencies: ["MTGGoldfish", "EDHREC"],
    explanation: "Measures the likelihood that future supply pressure could reduce upside.",
  },
  {
    id: "market-confidence",
    name: "Market Confidence",
    signalName: "MarketConfidence",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket"],
    explanation: "Measures reliability of the normalized market estimate.",
  },
  {
    id: "playability",
    name: "Playability Intelligence",
    signalName: "Playability",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Game Knowledge"],
    futureDependencies: ["EDHREC", "MTGGoldfish"],
    explanation: "Future model for format demand, metagame usage, and deck relevance.",
  },
  {
    id: "grading",
    name: "Grading Intelligence",
    signalName: "GradingPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Condition Profile"],
    futureDependencies: ["PSA", "CGC", "BGS"],
    explanation: "Measures grading potential from condition and collector profile.",
  },
  {
    id: "regional",
    name: "Regional Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["LigaMagic", "Cardmarket", "Currency Engine"],
    explanation: "Future model for regional valuation, demand, liquidity, tax, shipping, and currency effects.",
  },
  {
    id: "behavior",
    name: "Behavior Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["User behavior history"],
    explanation: "Future model for buyer-specific patterns and execution behavior.",
  },
  {
    id: "historical",
    name: "Historical Intelligence",
    signalName: "HistoricalStability",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for trend stability, drawdowns, and historical support.",
  },
  {
    id: "volatility",
    name: "Volatility Intelligence",
    signalName: "Volatility",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for price movement risk and short-term instability.",
  },
  {
    id: "demand",
    name: "Demand Intelligence",
    signalName: "Demand",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Market Context"],
    futureDependencies: ["TCGplayer", "eBay", "EDHREC", "MTGGoldfish"],
    explanation: "Future model for buyer demand, format popularity, and marketplace velocity.",
  },
  {
    id: "scarcity",
    name: "Scarcity Intelligence",
    signalName: "Scarcity",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall"],
    futureDependencies: ["Print run data", "Population reports"],
    explanation: "Measures relative scarcity from rarity, printing metadata, and future supply signals.",
  },
];

export function getIndicatorMetadata(id: string) {
  return indicatorRegistry.find((indicator) => indicator.id === id);
}
