import type { IndicatorMetadata } from "@/lib/intelligence/framework/IndicatorMetadata";

export const indicatorRegistry: IndicatorMetadata[] = [
  {
    id: "investment-potential",
    name: "Investment Potential",
    signalName: "InvestmentPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Scryfall Market Provider"],
    futureDependencies: ["Historical Intelligence", "Regional Intelligence"],
    explanation: "Measures long-term asset potential from current card, printing, and market context.",
  },
  {
    id: "collector-appeal",
    name: "Collector Appeal",
    signalName: "CollectorAppeal",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall"],
    futureDependencies: ["PSA", "CGC", "BGS"],
    explanation: "Measures collector desirability from printing prestige, treatment, product family, and finish.",
  },
  {
    id: "liquidity",
    name: "Liquidity",
    signalName: "Liquidity",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket", "LigaMagic"],
    explanation: "Measures how easily the asset can be resold once live marketplace depth exists.",
  },
  {
    id: "reprint-risk",
    name: "Reprint Risk",
    signalName: "ReprintRisk",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall"],
    futureDependencies: ["MTGGoldfish", "EDHREC"],
    explanation: "Measures the likelihood that future supply pressure could reduce upside.",
  },
  {
    id: "market-confidence",
    name: "Market Confidence",
    signalName: "MarketConfidence",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket"],
    explanation: "Measures reliability of the normalized market estimate.",
  },
  {
    id: "playability",
    name: "Playability Intelligence",
    signalName: "Playability",
    playabilityIndicatorName: "overallPlayability",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Measures format legality and prepares for metagame usage, deck penetration, and play demand providers.",
  },
  {
    id: "commander-strength",
    name: "Commander Strength",
    playabilityIndicatorName: "commanderStrength",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC"],
    explanation: "Measures Commander availability now and prepares for future EDHREC deck penetration.",
  },
  {
    id: "competitive-strength",
    name: "Competitive Strength",
    playabilityIndicatorName: "competitiveStrength",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Averages tracked competitive format availability until metagame providers are connected.",
  },
  {
    id: "casual-strength",
    name: "Casual Strength",
    playabilityIndicatorName: "casualStrength",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "Canadian Highlander providers"],
    explanation: "Prepared for casual demand sources, with Commander legality available now.",
  },
  {
    id: "ban-risk",
    name: "Ban Risk",
    playabilityIndicatorName: "banRisk",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["Format rules feeds"],
    explanation: "Tracks current legal, restricted, banned, or unknown status per format.",
  },
  {
    id: "format-diversity",
    name: "Format Diversity",
    playabilityIndicatorName: "formatDiversity",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Measures breadth of tracked formats where a card can legally create demand.",
  },
  {
    id: "meta-stability",
    name: "Meta Stability",
    playabilityIndicatorName: "metaStability",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder"],
    futureDependencies: ["Melee", "MTGO", "Top8", "MTGGoldfish"],
    explanation: "Architecture-only indicator for future metagame stability.",
  },
  {
    id: "playability-trend",
    name: "Playability Trend",
    playabilityIndicatorName: "trend",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Architecture-only indicator for increasing, stable, declining, or unknown play demand.",
  },
  {
    id: "grading",
    name: "Grading Intelligence",
    signalName: "GradingPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Condition Profile"],
    futureDependencies: ["PSA", "CGC", "BGS"],
    explanation: "Measures grading potential from condition and collector profile.",
  },
  {
    id: "regional",
    name: "Regional Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["LigaMagic", "Cardmarket", "Currency Engine"],
    explanation: "Future model for regional valuation, demand, liquidity, tax, shipping, and currency effects.",
  },
  {
    id: "behavior",
    name: "Behavior Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["User behavior history"],
    explanation: "Future model for buyer-specific patterns and execution behavior.",
  },
  {
    id: "historical",
    name: "Historical Intelligence",
    signalName: "HistoricalStability",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for trend stability, drawdowns, and historical support.",
  },
  {
    id: "volatility",
    name: "Volatility Intelligence",
    signalName: "Volatility",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for price movement risk and short-term instability.",
  },
  {
    id: "demand",
    name: "Demand Intelligence",
    signalName: "Demand",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Market Context"],
    futureDependencies: ["TCGplayer", "eBay", "EDHREC", "MTGGoldfish"],
    explanation: "Future model for buyer demand, format popularity, and marketplace velocity.",
  },
  {
    id: "scarcity",
    name: "Scarcity Intelligence",
    signalName: "Scarcity",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall"],
    futureDependencies: ["Print run data", "Population reports"],
    explanation: "Measures relative scarcity from rarity, printing metadata, and future supply signals.",
  },
];

export function getIndicatorMetadata(id: string) {
  return indicatorRegistry.find((indicator) => indicator.id === id);
}
