import type { IndicatorMetadata } from "@/lib/intelligence/framework/IndicatorMetadata";

export const indicatorRegistry: IndicatorMetadata[] = [
  {
    id: "investment-potential",
    name: "Investment Potential",
    signalName: "InvestmentPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Scryfall Market Provider"],
    futureDependencies: ["Historical Intelligence", "Regional Intelligence"],
    explanation: "Measures long-term asset potential from current card, printing, and market context.",
  },
  {
    id: "collector-appeal",
    name: "Collector Appeal",
    signalName: "CollectorAppeal",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Certification Intelligence"],
    futureDependencies: ["PSA", "CGC", "BGS", "TAG", "SGC", "ARS"],
    explanation:
      "Measures collector desirability from printing prestige, treatment, product family, finish, and Certification Intelligence.",
  },
  {
    id: "certification-grade",
    name: "Certification Grade",
    certificationIndicatorName: "certificationGrade",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["PSA", "BGS", "CGC", "TAG", "SGC", "ARS"],
    explanation: "Measures overall certification characteristics across registered providers.",
  },
  {
    id: "population-scarcity",
    name: "Population Scarcity",
    certificationIndicatorName: "populationScarcity",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Official population reports"],
    explanation: "Measures certified population scarcity when official provider data exists.",
  },
  {
    id: "gem-rate",
    name: "Gem Rate",
    certificationIndicatorName: "gemRate",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Official gem population reports"],
    explanation: "Measures gem population share when official provider data exists.",
  },
  {
    id: "certification-premium",
    name: "Certification Premium",
    certificationIndicatorName: "certificationPremium",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Official graded sales providers"],
    explanation: "Measures estimated certified premium as a collectible characteristic.",
  },
  {
    id: "population-trend",
    name: "Population Trend",
    certificationIndicatorName: "populationTrend",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Population Growth"],
    explanation: "Measures provider-ready population movement over time.",
  },
  {
    id: "collector-competition",
    name: "Collector Competition",
    certificationIndicatorName: "collectorCompetition",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Official graded sales providers"],
    explanation: "Measures likely competition among certified-card collectors.",
  },
  {
    id: "submission-saturation",
    name: "Submission Saturation",
    certificationIndicatorName: "submissionSaturation",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Placeholder Certification Provider"],
    futureDependencies: ["Population Growth"],
    explanation: "Measures future submission crowding once population growth is available.",
  },
  {
    id: "liquidity",
    name: "Liquidity",
    signalName: "Liquidity",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket", "LigaMagic"],
    explanation: "Measures how easily the asset can be resold once live marketplace depth exists.",
  },
  {
    id: "reprint-risk",
    name: "Reprint Risk",
    signalName: "ReprintRisk",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall"],
    futureDependencies: ["MTGGoldfish", "EDHREC"],
    explanation: "Measures the likelihood that future supply pressure could reduce upside.",
  },
  {
    id: "market-confidence",
    name: "Market Confidence",
    signalName: "MarketConfidence",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall Market Provider"],
    futureDependencies: ["TCGplayer", "eBay", "Cardmarket"],
    explanation: "Measures reliability of the normalized market estimate.",
  },
  {
    id: "playability",
    name: "Overall Playability",
    signalName: "Playability",
    playabilityIndicatorName: "overallPlayability",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Measures weighted player demand across currently supported formats.",
  },
  {
    id: "commander-strength",
    name: "Commander Strength",
    playabilityIndicatorName: "commanderStrength",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC"],
    explanation: "Measures Commander demand, casual relevance, and multiplayer adoption readiness.",
  },
  {
    id: "competitive-strength",
    name: "Competitive Strength",
    playabilityIndicatorName: "competitiveStrength",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Measures competitive demand across weighted constructed formats.",
  },
  {
    id: "casual-strength",
    name: "Casual Strength",
    playabilityIndicatorName: "casualStrength",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "Canadian Highlander providers"],
    explanation: "Measures casual and multiplayer demand with Commander as the strongest current signal.",
  },
  {
    id: "ban-risk",
    name: "Ban Risk",
    playabilityIndicatorName: "banRisk",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["Format rules feeds"],
    explanation: "Tracks current legal, restricted, banned, or unknown status per format.",
  },
  {
    id: "format-diversity",
    name: "Format Diversity",
    playabilityIndicatorName: "formatDiversity",
    version: "1.0.0",
    status: "LIVE",
    dataSources: ["Scryfall"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Top8"],
    explanation: "Measures breadth of tracked formats where a card can create player demand.",
  },
  {
    id: "demand-stability",
    name: "Demand Stability",
    playabilityIndicatorName: "demandStability",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Format weights"],
    futureDependencies: ["Melee", "MTGO", "Top8", "MTGGoldfish"],
    explanation: "Measures whether demand appears stable across currently playable formats.",
  },
  {
    id: "meta-dependency",
    name: "Meta Dependency",
    playabilityIndicatorName: "metaDependency",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Format weights"],
    futureDependencies: ["MTGGoldfish", "Melee", "MTGO", "Tournament APIs"],
    explanation: "Measures how much demand depends on competitive metagame presence.",
  },
  {
    id: "future-demand-readiness",
    name: "Future Demand Readiness",
    playabilityIndicatorName: "futureDemandReadiness",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall", "Format weights"],
    futureDependencies: ["EDHREC", "MTGGoldfish", "Melee", "MTGO", "Tournament APIs"],
    explanation: "Measures readiness for richer demand signals as future play providers connect.",
  },
  {
    id: "grading",
    name: "Grading Intelligence",
    signalName: "GradingPotential",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Condition Profile"],
    futureDependencies: ["PSA", "CGC", "BGS"],
    explanation: "Measures grading potential from condition and collector profile.",
  },
  {
    id: "regional",
    name: "Regional Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["LigaMagic", "Cardmarket", "Currency Engine"],
    explanation: "Future model for regional valuation, demand, liquidity, tax, shipping, and currency effects.",
  },
  {
    id: "behavior",
    name: "Behavior Intelligence",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["User behavior history"],
    explanation: "Future model for buyer-specific patterns and execution behavior.",
  },
  {
    id: "historical",
    name: "Historical Intelligence",
    signalName: "HistoricalStability",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for trend stability, drawdowns, and historical support.",
  },
  {
    id: "volatility",
    name: "Volatility Intelligence",
    signalName: "Volatility",
    version: "1.0.0",
    status: "WAITING_FOR_PROVIDER",
    dataSources: [],
    futureDependencies: ["Historical price storage"],
    explanation: "Future model for price movement risk and short-term instability.",
  },
  {
    id: "demand",
    name: "Demand Intelligence",
    signalName: "Demand",
    version: "1.0.0",
    status: "PLACEHOLDER",
    dataSources: ["Market Context"],
    futureDependencies: ["TCGplayer", "eBay", "EDHREC", "MTGGoldfish"],
    explanation: "Future model for buyer demand, format popularity, and marketplace velocity.",
  },
  {
    id: "scarcity",
    name: "Scarcity Intelligence",
    signalName: "Scarcity",
    version: "1.0.0",
    status: "ESTIMATED",
    dataSources: ["Scryfall"],
    futureDependencies: ["Print run data", "Population reports"],
    explanation: "Measures relative scarcity from rarity, printing metadata, and future supply signals.",
  },
];

export function getIndicatorMetadata(id: string) {
  return indicatorRegistry.find((indicator) => indicator.id === id);
}
