import type { CanonicalEntry } from "@/types/canonicalEntry";

export const canonicalDictionary: CanonicalEntry[] = [
  {
    canonicalIdentity: "Lightning Bolt",
    aliases: ["lightning bolt"],
    nicknames: ["bolt"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 32,
    priority: 100,
    communityPopularity: 100,
    professionalUsage: 100,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
    notes: "Default professional shorthand for Lightning Bolt.",
  },
  {
    canonicalIdentity: "Birds of Paradise",
    aliases: ["birds of paradise"],
    nicknames: ["birds", "bop"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 30,
    priority: 96,
    communityPopularity: 94,
    professionalUsage: 92,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Force of Will",
    aliases: ["force of will"],
    nicknames: ["force"],
    abbreviations: ["fow"],
    game: "Magic",
    confidenceWeight: 33,
    priority: 98,
    communityPopularity: 98,
    professionalUsage: 99,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Force of Negation",
    aliases: ["force of negation"],
    nicknames: ["force"],
    abbreviations: ["fon"],
    game: "Magic",
    confidenceWeight: 24,
    priority: 82,
    communityPopularity: 85,
    professionalUsage: 84,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Force of Vigor",
    aliases: ["force of vigor"],
    nicknames: ["force"],
    abbreviations: ["fov"],
    game: "Magic",
    confidenceWeight: 22,
    priority: 76,
    communityPopularity: 78,
    professionalUsage: 78,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Dark Confidant",
    aliases: ["dark confidant"],
    nicknames: ["bob"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 32,
    priority: 95,
    communityPopularity: 96,
    professionalUsage: 96,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Jace, the Mind Sculptor",
    aliases: ["jace the mind sculptor", "jace, the mind sculptor"],
    nicknames: ["the mind sculptor"],
    abbreviations: ["jtms"],
    game: "Magic",
    confidenceWeight: 32,
    priority: 94,
    communityPopularity: 95,
    professionalUsage: 95,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Deathrite Shaman",
    aliases: ["deathrite shaman"],
    nicknames: [],
    abbreviations: ["drs"],
    game: "Magic",
    confidenceWeight: 31,
    priority: 92,
    communityPopularity: 93,
    professionalUsage: 93,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Tarmogoyf",
    aliases: ["tarmogoyf"],
    nicknames: ["goyf"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 30,
    priority: 91,
    communityPopularity: 94,
    professionalUsage: 92,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Snapcaster Mage",
    aliases: ["snapcaster mage"],
    nicknames: ["snap"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 30,
    priority: 90,
    communityPopularity: 92,
    professionalUsage: 90,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Ragavan, Nimble Pilferer",
    aliases: ["ragavan", "ragavan nimble pilferer", "ragavan, nimble pilferer"],
    nicknames: ["monkey"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 31,
    priority: 93,
    communityPopularity: 97,
    professionalUsage: 95,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Black Lotus",
    aliases: ["black lotus"],
    nicknames: ["lotus"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 34,
    priority: 99,
    communityPopularity: 100,
    professionalUsage: 100,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Grapeshot",
    aliases: ["grapeshot"],
    nicknames: ["storm"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 18,
    priority: 60,
    communityPopularity: 72,
    professionalUsage: 70,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
    notes: "Context-aware placeholder until archetype resolution exists.",
  },
  {
    canonicalIdentity: "Urza Tron Archetype",
    aliases: ["urza tron"],
    nicknames: ["tron"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 10,
    priority: 20,
    communityPopularity: 88,
    professionalUsage: 82,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
    notes: "TODO: Resolve archetypes separately from card identities.",
    futureMetadata: { type: "archetype" },
  },
  {
    canonicalIdentity: "Fetch Land",
    aliases: ["fetch land"],
    nicknames: ["fetch"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 10,
    priority: 18,
    communityPopularity: 90,
    professionalUsage: 86,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
    notes: "TODO: Resolve land cycles separately from card identities.",
    futureMetadata: { type: "cycle" },
  },
  {
    canonicalIdentity: "Counterspell",
    aliases: ["counterspell"],
    nicknames: ["counter"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 26,
    priority: 75,
    communityPopularity: 88,
    professionalUsage: 84,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Swords to Plowshares",
    aliases: ["swords to plowshares"],
    nicknames: ["swords"],
    abbreviations: ["stp"],
    game: "Magic",
    confidenceWeight: 29,
    priority: 86,
    communityPopularity: 91,
    professionalUsage: 89,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Path to Exile",
    aliases: ["path to exile"],
    nicknames: ["path"],
    abbreviations: ["pte"],
    game: "Magic",
    confidenceWeight: 26,
    priority: 80,
    communityPopularity: 86,
    professionalUsage: 82,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Stoneforge Mystic",
    aliases: ["stoneforge mystic"],
    nicknames: ["stoneforge"],
    abbreviations: ["sfm"],
    game: "Magic",
    confidenceWeight: 28,
    priority: 84,
    communityPopularity: 88,
    professionalUsage: 86,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Delver of Secrets",
    aliases: ["delver of secrets"],
    nicknames: ["delver"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 27,
    priority: 83,
    communityPopularity: 88,
    professionalUsage: 84,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Murktide Regent",
    aliases: ["murktide regent"],
    nicknames: ["murktide"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 26,
    priority: 82,
    communityPopularity: 86,
    professionalUsage: 84,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Orcish Bowmasters",
    aliases: ["orcish bowmasters"],
    nicknames: ["bowmasters"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 27,
    priority: 87,
    communityPopularity: 90,
    professionalUsage: 89,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "The One Ring",
    aliases: ["the one ring"],
    nicknames: ["ring"],
    abbreviations: ["tor"],
    game: "Magic",
    confidenceWeight: 27,
    priority: 87,
    communityPopularity: 91,
    professionalUsage: 89,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Uro, Titan of Nature's Wrath",
    aliases: ["uro", "uro titan of nature's wrath"],
    nicknames: ["uro"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 25,
    priority: 78,
    communityPopularity: 84,
    professionalUsage: 80,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
  {
    canonicalIdentity: "Omnath, Locus of Creation",
    aliases: ["omnath locus of creation"],
    nicknames: ["omnath"],
    abbreviations: [],
    game: "Magic",
    confidenceWeight: 23,
    priority: 74,
    communityPopularity: 80,
    professionalUsage: 76,
    futureSearchFrequency: 0,
    futureUserWeight: 0,
  },
];
