export type ParserFixture = {
  query: string;
  expected: string[];
};

export const parserFixtures: ParserFixture[] = [
  { query: "Black Lotus Alpha LP", expected: ["set", "condition"] },
  { query: "Bolt Judge", expected: ["promo"] },
  { query: "Bolt Secret", expected: ["promo"] },
  { query: "Force EMA JP HP", expected: ["language", "condition"] },
  { query: "Ragavan MH2 Retro Foil", expected: ["setCode", "frame", "finish"] },
  { query: "Sol Ring Masterpiece", expected: ["treatment"] },
  { query: "Luffy Manga OP05", expected: ["treatment", "setCode"] },
  { query: "Pikachu Poncho PSA10", expected: ["grading"] },
  { query: "Counterspell Textless", expected: ["treatment"] },
  { query: "Birds Promo", expected: ["promo"] },
  { query: "Urza Store Championship", expected: ["promo"] },
  { query: "Black Lotus 30A", expected: ["promo"] },
  { query: "Lightning Bolt English NM", expected: ["language", "condition"] },
  { query: "Counterspell Japanese Foil", expected: ["language", "finish"] },
  { query: "Mana Drain Italian LP", expected: ["language", "condition"] },
  { query: "Mox Opal Judge Promo", expected: ["promo"] },
  { query: "Mox Diamond Stronghold HP", expected: ["condition"] },
  { query: "Chrome Mox Mirrodin NM", expected: ["condition"] },
  { query: "Rhystic Study WOE Confetti", expected: ["setCode", "finish"] },
  { query: "Doubling Season WOE anime", expected: ["setCode", "treatment"] },
  { query: "Sheoldred DMU textured foil", expected: ["setCode", "finish"] },
  { query: "The One Ring LTR poster foil", expected: ["setCode", "finish"] },
  { query: "Orcish Bowmasters LTR borderless", expected: ["setCode", "frame"] },
  { query: "Fable NEO showcase", expected: ["setCode", "frame"] },
  { query: "Boseiju NEO borderless JP", expected: ["setCode", "frame", "language"] },
  { query: "Atraxa ONE oil slick", expected: ["setCode", "treatment"] },
  { query: "Elesh Norn ONE step and compleat", expected: ["setCode"] },
  { query: "Jeweled Lotus Commander Masters", expected: ["set"] },
  { query: "Dockside Extortionist Double Masters", expected: ["set"] },
  { query: "Fierce Guardianship Commander", expected: ["set"] },
  { query: "Fury MH2 etched", expected: ["setCode", "finish"] },
  { query: "Endurance MH2 retro foil", expected: ["setCode", "frame", "finish"] },
  { query: "Solitude MH2 old border", expected: ["setCode", "frame"] },
  { query: "Subtlety MH2 nonfoil", expected: ["setCode", "finish"] },
  { query: "Grief MH2 showcase", expected: ["setCode", "frame"] },
  { query: "Wrenn and Six MH1 foil", expected: ["setCode", "finish"] },
  { query: "Urza Lord High Artificer MH1", expected: ["setCode"] },
  { query: "Yawgmoth MH1 retro", expected: ["setCode", "frame"] },
  { query: "Teferi Dominaria mythic", expected: ["rarity"] },
  { query: "Karn WAR JP", expected: ["setCode", "language"] },
  { query: "Nissa WAR stained glass", expected: ["setCode"] },
  { query: "Liliana Dreadhorde WAR foil", expected: ["setCode", "finish"] },
  { query: "Ugin Fate Reforged LP", expected: ["condition"] },
  { query: "Sorin KTK NM", expected: ["setCode", "condition"] },
  { query: "Thoughtseize Theros HP", expected: ["condition"] },
  { query: "Mutavault M14 MP", expected: ["condition"] },
  { query: "Snapcaster ISD Russian", expected: ["setCode", "language"] },
  { query: "Liliana ISD German LP", expected: ["setCode", "language", "condition"] },
  { query: "Cavern AVR Spanish", expected: ["language"] },
  { query: "Emrakul ROE Portuguese", expected: ["language"] },
  { query: "Jace WWK Japanese", expected: ["language"] },
  { query: "Stoneforge WWK GP", expected: ["promo"] },
  { query: "Tarmogoyf Future Sight", expected: ["frame"] },
  { query: "Dark Confidant RAV Italian", expected: ["setCode", "language"] },
  { query: "Glimpse CHK foil", expected: ["setCode", "finish"] },
  { query: "Aether Vial DST", expected: [] },
  { query: "Skullclamp DST HP", expected: ["condition"] },
  { query: "Chrome Mox MRD foil", expected: ["setCode", "finish"] },
  { query: "Polluted Delta ONS LP", expected: ["setCode", "condition"] },
  { query: "Flooded Strand ONS NM", expected: ["setCode", "condition"] },
  { query: "Cabal Coffers TOR", expected: [] },
  { query: "Entomb ODY judge", expected: ["promo"] },
  { query: "Phyrexian Dreadnought MIR", expected: ["setCode"] },
  { query: "Lion's Eye Diamond MIR damaged", expected: ["setCode", "condition"] },
  { query: "Gaea's Cradle USG LP", expected: ["setCode", "condition"] },
  { query: "Serra's Sanctum USG NM", expected: ["setCode", "condition"] },
  { query: "Survival EXO played", expected: ["condition"] },
  { query: "City of Traitors EXO good", expected: ["condition"] },
  { query: "Mox Diamond STH fair", expected: ["condition"] },
  { query: "Wasteland TMP excellent", expected: ["setCode", "condition"] },
  { query: "Force of Will ALL LP", expected: ["condition"] },
  { query: "Underground Sea Revised HP", expected: ["condition"] },
  { query: "Volcanic Island 3ED NM", expected: ["condition"] },
  { query: "Library Alexandria ARN", expected: ["setCode"] },
  { query: "Mishra's Workshop ATQ", expected: ["setCode"] },
  { query: "Tabernacle LEG Italian", expected: ["setCode", "language"] },
  { query: "Nether Void LEG", expected: ["setCode"] },
  { query: "Mana Crypt media promo", expected: ["promo"] },
  { query: "Vampiric Tutor judge foil", expected: ["promo", "finish"] },
  { query: "Demonic Tutor mystical archive etched", expected: ["finish"] },
  { query: "Brainstorm secret lair", expected: ["promo"] },
  { query: "Serra Angel retro foil", expected: ["frame", "finish"] },
  { query: "Shivan Dragon old border", expected: ["frame"] },
  { query: "Swords to Plowshares textless", expected: ["treatment"] },
  { query: "Path to Exile full art", expected: ["treatment"] },
  { query: "Ragavan serialized", expected: ["treatment"] },
  { query: "Atraxa raised foil", expected: ["treatment"] },
  { query: "Mana Crypt neon", expected: ["treatment"] },
  { query: "Ulamog fractured foil", expected: ["treatment", "finish"] },
  { query: "Bitterblossom judge NM", expected: ["promo", "condition"] },
  { query: "Pokemon Charizard JP PSA10", expected: ["game", "language", "grading"] },
  { query: "Pokemon Pikachu poncho", expected: ["game"] },
  { query: "One Piece Luffy manga op05", expected: ["game", "treatment", "setCode"] },
  { query: "OnePiece Nami SP", expected: ["game", "condition"] },
  { query: "Lorcana Elsa enchanted", expected: ["game"] },
  { query: "Lorcana Stitch foil", expected: ["game", "finish"] },
  { query: "FAB Tunic rainbow foil", expected: ["game", "finish"] },
  { query: "Flesh and Blood Command and Conquer HP", expected: ["game", "condition"] },
  { query: "Black Lotus signed artist proof", expected: [] },
  { query: "Counterspell altered misprint", expected: [] },
  { query: "Mox Pearl beta poor", expected: ["condition"] },
  { query: "Mox Sapphire alpha mint", expected: ["condition"] },
  { query: "Time Walk collector edition", expected: ["set"] },
  { query: "Ancestral Recall international collector", expected: ["set"] },
  { query: "Bolt foil nm", expected: ["finish", "condition"] },
  { query: "Bolt retro lp", expected: ["frame", "condition"] },
  { query: "Bolt textless hp", expected: ["treatment", "condition"] },
  { query: "Birds masterpiece foil", expected: ["treatment", "finish"] },
  { query: "Birds judge jp", expected: ["promo", "language"] },
  { query: "Counterspell anime jp", expected: ["treatment", "language"] },
  { query: "Counterspell secret lair foil", expected: ["promo", "finish"] },
  { query: "Counterspell judge promo", expected: ["promo"] },
  { query: "Sol Ring invention foil", expected: ["treatment", "finish"] },
  { query: "Sol Ring retro nonfoil", expected: ["frame", "finish"] },
  { query: "Sol Ring Commander lp", expected: ["set", "condition"] },
  { query: "Ragavan MH2 etched nm", expected: ["setCode", "finish", "condition"] },
  { query: "Ragavan serialized foil", expected: ["treatment", "finish"] },
  { query: "Ragavan showcase jp", expected: ["frame", "language"] },
  { query: "Black Lotus alpha nm", expected: ["set", "condition"] },
  { query: "Black Lotus beta hp", expected: ["condition"] },
  { query: "Black Lotus 30th sealed", expected: ["promo"] },
  { query: "Black Lotus 30a lp", expected: ["promo", "condition"] },
  { query: "Force EMA japanese hp", expected: ["language", "condition"] },
  { query: "Force judge foil", expected: ["promo", "finish"] },
  { query: "Force old border foil", expected: ["frame", "finish"] },
  { query: "Force of Will borderless", expected: ["frame"] },
  { query: "Force of Will etched", expected: ["finish"] },
  { query: "Luffy manga op05 jp", expected: ["treatment", "setCode", "language"] },
  { query: "Luffy OP05 sp", expected: ["setCode", "condition"] },
  { query: "Zoro sp op06", expected: ["condition"] },
  { query: "Zoro manga onepiece", expected: ["treatment", "game"] },
  { query: "Nami manga op05", expected: ["treatment", "setCode"] },
  { query: "Pikachu poncho japanese psa10", expected: ["language", "grading"] },
  { query: "Pikachu promo lp", expected: ["promo", "condition"] },
  { query: "Charizard base jp hp", expected: ["language", "condition"] },
  { query: "Charizard base set shadowless", expected: [] },
  { query: "Charizard gold star mp", expected: ["condition"] },
  { query: "Lorcana Elsa enchanted foil", expected: ["game", "finish"] },
  { query: "Lorcana Mickey enchanted", expected: ["game"] },
  { query: "Lorcana Stitch promo", expected: ["game", "promo"] },
  { query: "FAB Tunic cold foil", expected: ["game", "finish"] },
  { query: "FAB Command and Conquer rainbow", expected: ["game", "finish"] },
  { query: "Flesh and Blood Art of War HP", expected: ["game", "condition"] },
  { query: "Mana Crypt invention", expected: ["treatment"] },
  { query: "Mana Crypt masterpiece", expected: ["treatment"] },
  { query: "Mana Crypt judge foil", expected: ["promo", "finish"] },
  { query: "Mana Crypt media promo nm", expected: ["promo", "condition"] },
  { query: "Demonic Tutor judge lp", expected: ["promo", "condition"] },
  { query: "Demonic Tutor retro foil", expected: ["frame", "finish"] },
  { query: "Demonic Tutor etched jp", expected: ["finish", "language"] },
  { query: "Vampiric Tutor sld foil", expected: ["promo", "finish"] },
  { query: "Mystical Tutor promo pack", expected: ["promo"] },
  { query: "Enlightened Tutor old border", expected: ["frame"] },
  { query: "Worldly Tutor judge", expected: ["promo"] },
  { query: "Imperial Seal judge foil", expected: ["promo", "finish"] },
  { query: "Imperial Seal 2x2 borderless", expected: ["frame"] },
  { query: "Dockside extortionist etched", expected: ["finish"] },
  { query: "Dockside extortionist judge", expected: ["promo"] },
  { query: "Jeweled Lotus textured foil", expected: ["finish"] },
  { query: "Jeweled Lotus extended art", expected: ["treatment"] },
  { query: "Fierce Guardianship extended", expected: ["frame"] },
  { query: "Deflecting Swat commander", expected: ["set"] },
  { query: "Cyclonic Rift masterpiece", expected: ["treatment"] },
  { query: "Cyclonic Rift invention", expected: ["treatment"] },
  { query: "Rhystic Study judge foil", expected: ["promo", "finish"] },
  { query: "Rhystic Study anime confetti", expected: ["treatment", "finish"] },
  { query: "Smothering Tithe borderless foil", expected: ["frame", "finish"] },
  { query: "Esper Sentinel retro foil", expected: ["frame", "finish"] },
  { query: "Esper Sentinel old border", expected: ["frame"] },
  { query: "The One Ring serialized", expected: ["treatment"] },
  { query: "The One Ring poster foil", expected: ["finish"] },
  { query: "Orcish Bowmasters showcase", expected: ["frame"] },
  { query: "Orcish Bowmasters surge foil", expected: ["finish"] },
  { query: "Sheoldred showcase foil", expected: ["frame", "finish"] },
  { query: "Sheoldred phyrexian jp", expected: ["language"] },
  { query: "Atraxa oil slick foil", expected: ["treatment", "finish"] },
  { query: "Atraxa raised foil lp", expected: ["treatment", "finish", "condition"] },
  { query: "Elesh Norn oil slick", expected: ["treatment"] },
  { query: "Vorinclex showcase foil", expected: ["frame", "finish"] },
  { query: "Jin Gitaxias neon", expected: ["treatment"] },
  { query: "Urza textless foil", expected: ["treatment", "finish"] },
  { query: "Urza store championship foil", expected: ["promo", "finish"] },
  { query: "Urza judge promo", expected: ["promo"] },
  { query: "Urza retro foil", expected: ["frame", "finish"] },
  { query: "Mox Opal judge foil", expected: ["promo", "finish"] },
  { query: "Mox Opal masterpiece", expected: ["treatment"] },
  { query: "Mox Amber retro", expected: ["frame"] },
  { query: "Mox Diamond judge", expected: ["promo"] },
  { query: "Mox Pearl alpha lp", expected: ["set", "condition"] },
  { query: "Mox Jet beta hp", expected: ["condition"] },
  { query: "Mox Ruby 30a", expected: ["promo"] },
  { query: "Mox Emerald collector edition", expected: ["set"] },
  { query: "Mox Sapphire international collector", expected: ["set"] },
  { query: "Time Vault unlimited mp", expected: ["condition"] },
  { query: "Timetwister alpha nm", expected: ["set", "condition"] },
  { query: "Wheel of Fortune judge", expected: ["promo"] },
  { query: "Wheel of Fortune revised lp", expected: ["condition"] },
  { query: "Bazaar Arabian Nights", expected: [] },
  { query: "Library ARN hp", expected: ["setCode", "condition"] },
  { query: "Workshop ATQ lp", expected: ["setCode", "condition"] },
  { query: "Candelabra ATQ nm", expected: ["setCode", "condition"] },
  { query: "Chains LEG italian", expected: ["setCode", "language"] },
  { query: "Moat LEG french", expected: ["setCode", "language"] },
  { query: "Abyss LEG german", expected: ["setCode", "language"] },
  { query: "lightning bolt judge", expected: ["promo"] },
  { query: "fire ice split", expected: [] },
  { query: "bonecrusher giant adventure", expected: [] },
  { query: "fable reflection token", expected: [] },
  { query: "emergent ultimatum modal dfc", expected: [] },
  { query: "lotus token", expected: [] },
  { query: "counterspell textless", expected: ["treatment"] },
  { query: "birds promo", expected: ["promo"] },
  { query: "ragavan mh2", expected: ["setCode"] },
  { query: "black lotus alpha", expected: ["set"] },
  { query: "delver transform back face", expected: [] },
  { query: "brisela meld", expected: [] },
  { query: "chandra emblem", expected: [] },
  { query: "planechase plane", expected: [] },
  { query: "scheme archenemy", expected: [] },
  { query: "secret lair lightning bolt foil", expected: ["promo", "finish"] },
  { query: "judge counterspell foil", expected: ["promo", "finish"] },
  { query: "emeritus lightning bolt back face", expected: [] },
  { query: "brazen borrower adventure foil", expected: ["finish"] },
  { query: "wear tear split card", expected: [] },
  { query: "bolt judge foil", expected: ["promo", "finish"] },
  { query: "bolt retro", expected: ["frame"] },
  { query: "bolt sld", expected: ["promo"] },
  { query: "birds foil", expected: ["finish"] },
  { query: "bob", expected: [] },
  { query: "jtms", expected: [] },
  { query: "fow", expected: [] },
  { query: "drs", expected: [] },
  { query: "goyf", expected: [] },
  { query: "snap", expected: [] },
  { query: "lotus alpha", expected: ["set"] },
  { query: "ragavan monkey", expected: [] },
  { query: "force hp", expected: ["condition"] },
  { query: "counterspell anime", expected: ["treatment"] },
  { query: "luffy manga op05", expected: ["treatment", "setCode"] },
  { query: "pikachu poncho psa10", expected: ["grading"] },
  { query: "charizard base jp", expected: ["language"] },
  { query: "stp judge", expected: ["promo"] },
  { query: "swords old border", expected: ["frame"] },
  { query: "path promo foil", expected: ["promo", "finish"] },
  { query: "pte borderless", expected: ["frame"] },
  { query: "sfm gp", expected: ["promo"] },
  { query: "stoneforge judge foil", expected: ["promo", "finish"] },
  { query: "delver retro foil", expected: ["frame", "finish"] },
  { query: "murktide mh2 foil", expected: ["setCode", "finish"] },
  { query: "bowmasters ltr surge", expected: ["setCode", "finish"] },
  { query: "ring poster foil", expected: ["finish"] },
  { query: "uro etched", expected: ["finish"] },
  { query: "omnath showcase", expected: ["frame"] },
  { query: "force of negation retro", expected: ["frame"] },
  { query: "force of vigor foil", expected: ["finish"] },
  { query: "tron", expected: [] },
  { query: "fetch jp", expected: ["language"] },
  { query: "storm foil", expected: ["finish"] },
  { query: "monkey mh2 etched", expected: ["setCode", "finish"] },
  { query: "counterspell invocation", expected: ["treatment"] },
  { query: "counterspell invocatio", expected: ["treatment"] },
  { query: "counterspell invocat", expected: ["treatment"] },
  { query: "counterspell invoc", expected: ["treatment"] },
  { query: "counterspell inv", expected: ["treatment"] },
  { query: "counterspell in", expected: [] },
  { query: "bolt judg", expected: ["promo"] },
  { query: "bolt jud", expected: [] },
  { query: "bolt ju", expected: [] },
  { query: "ragavan retr", expected: ["frame"] },
  { query: "ragavan re", expected: [] },
  { query: "black lotus alph", expected: ["set"] },
  { query: "black lotus al", expected: [] },
  { query: "force ema jp hp", expected: ["set", "language", "condition"] },
  { query: "force eternal jp hp", expected: ["set", "language", "condition"] },
  { query: "sol ring invent", expected: ["treatment"] },
  { query: "sol ring inv", expected: ["treatment"] },
  { query: "textle bolt", expected: ["treatment"] },
  { query: "borderl counterspell", expected: ["frame"] },
  { query: "showca ragavan", expected: ["frame"] },
  { query: "serial ragavan", expected: ["treatment"] },
  { query: "prerele birds", expected: ["promo"] },
  { query: "urza's saga textless", expected: ["treatment"] },
  { query: "urzas saga textless", expected: ["treatment"] },
  { query: "urza saga textless", expected: ["treatment"] },
  { query: "urzas saga text less", expected: ["treatment"] },
  { query: "urza saga no text", expected: ["treatment"] },
  { query: "jace mind sculptor", expected: [] },
  { query: "thalia guardian thraben", expected: [] },
  { query: "ugin's labyrinth", expected: [] },
  { query: "fable mirror breaker", expected: [] },
];
